<a href="https://colab.research.google.com/github/sudhanshumukherjeexx/PyTorch-Deep-Learning/blob/main/Tensors_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS

- A torch.Tensor is a multi dimensional matrix containing elements of single data type.
- Similar to Numpy Arrays, but full of fun things that make them work better on GPU's(vs regular CPU's)
- default data type of float32
- More suitable for deep learning than a Numpy Array.

In [1]:
import torch
import numpy as np

# LISTS

In [4]:
my_list = [[1,2,3,4,5],[1,2,3,4,5]]
my_list

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

# NUMPY ARRAYS

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.81104569, 0.02672969, 0.0542019 , 0.25192424],
       [0.98163779, 0.18967936, 0.58106177, 0.23980547],
       [0.75119369, 0.903237  , 0.68372587, 0.40032591]])

In [8]:
np1 = np.random.rand(3)
np1

array([0.44651553, 0.11484816, 0.35494777])

In [9]:
np1 = np.random.randn(1,2)
np1

array([[0.68309808, 1.07051057]])

In [10]:
np1 = np.random.randn(10)
np1

array([-0.04568224,  1.16794264, -0.57743066,  1.16416355,  0.26736174,
       -1.53377385,  0.06768025,  0.31670712, -0.29972933,  0.27551546])

# TENSORS

In [2]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.4919, -0.2415, -0.0737, -0.2992],
        [-1.5475, -0.2467,  1.5862, -2.0295],
        [ 2.3857, -0.3209, -2.1511,  1.6487]])

In [4]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.6210, 0.4909, 0.4879, 0.1934],
        [0.8517, 0.9567, 0.4348, 0.9590],
        [0.4248, 0.4968, 0.6051, 0.8120]])

In [5]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## Create tensor out of Numpy Array

In [7]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8110, 0.0267, 0.0542, 0.2519],
        [0.9816, 0.1897, 0.5811, 0.2398],
        [0.7512, 0.9032, 0.6837, 0.4003]], dtype=torch.float64)

In [8]:
my_tensor.dtype

torch.float64

In [9]:
tensor_2d.dtype

torch.float32